### PR TITLE
Remove usethis dependency

### PR DESCRIPTION
**Pull request by olivroy**
Use cli instead as it is more lightweight. The `ui_*()` functions are no longer recommended. https://cli.r-lib.org/articles/usethis-ui.html

Also a few other code update. This brings down the number of dependencies from 112 to 101.

roxygen2 and assertthat are not needed as dependencies. (roxygen2 dep is declared via RoxygenNote field)

Close #9 

Happy to answer questions!

### CODE REVIEW

**Comment by giocomai** [comment]
Thanks a lot for this pull request and going through the move to `cli`, and overall, attention to details and context, much appreciated. Looks great!

**Comment by olivroy** [comment]
My pleasure, please do some tests interactively, and ping me if something is not working as expected, I will be happy to answer questions or make adjustments !

**Comment by olivroy** [comment]
I also noted that due to dplyr 1.1.0 join warnings, there are some noisy messages, https://github.com/EDJNet/tidywikidatar/actions/runs/7571605524/job/20619493768#step:6:281 but I couldn`t figure out where to apply the changes.

(pipes + inside mutate doesn`t give a precise traceback sometimes.)

**Comment by giocomai** [comment]
Well received, I'll do some additional checks before the next release!

**Pull request merged**
